# Syncs the "_build/html" folder with separate website repo to permit redirect

name: sync

# .github/workflows/git-sync.yml
on: push

jobs:
  git-sync:
    runs-on: ubuntu-latest
    steps:
      - name: git-sync
        uses: wei/git-sync@v3
        with:
          source_repo: "agully1/ca-knowledgebase/_build/html"
          source_branch: "main"
          destination_repo: "agully1/agully1.github.io"
          destination_branch: "main"
